name: Pipeline

on:
  push:
    branches: [main]

jobs:
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          echo "Install dependencies..."
          npm install
      - name: Run Linting
        run: |
          echo "Running Linting Tests..."
          npm run lint
        env:
          CI: true
  securityCheck:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Check for Security
        run: |
          echo "Checking security"
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [lintTest, securityCheck]
    steps:
      - name: Deploy
        run: |
          echo "Deployment in Progress..."